default:
  dora_dir: /home/hy17/Projects/audiocraft/saved_trainings
  partitions:
    global: debug
    team: debug
  reference_dir: /home/hy17/Projects/audiocraft
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /home/hy17/Projects/audiocraft/saved_trainings
  partitions:
    global: debug
    team: debug
  reference_dir: /home/hy17/Projects/audiocraft
